<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::create(
            [
                'role_id' => 2,
                'email' => 'bintangmangrove@gmail.com',
                'password' => bcrypt('Bintangmangrove1!'), // Password default
                'username' => 'BintangMangrove76',
                'name' => 'Bintang Mangrove',
                'whatsapp' => '081234567890',
                'address' => 'Gunung Anyar Tambak 3',
                'branch_id' => 1, // Anda mungkin perlu mengubah sesuai dengan nama cabang yang ada di database
                'saldo' => 0,
            ]
        );

        $users = [
            ['name' => 'Ika Maya W', 'username' => 'ikamaya1', 'address' => 'Amir Machmud VII/15 GN'],
            ['name' => 'Diadi Tri P', 'username' => 'diaditri1', 'address' => 'Amir Machmud VII/15 GN'],
            ['name' => 'Janutul F', 'username' => 'janatul76', 'address' => 'Gunung Anyar Tambak 3'],
            ['name' => 'Anas', 'username' => 'anas1', 'address' => 'GAT 1'],
            ['name' => 'Mulyati', 'username' => 'mulyati1', 'address' => 'GAT 1 RT 5'],
            ['name' => 'Nur Saadah', 'username' => 'nursaadah1', 'address' => 'GAT 2'],
            ['name' => 'Hamida', 'username' => 'hamida1', 'address' => 'Gunung Anyar Tambak 3'],
            ['name' => 'Kurdi', 'username' => 'kurdi1', 'address' => 'Gunung Anyar Tambak 3'],
            ['name' => 'Eko', 'username' => 'eko1', 'address' => 'Gunung Anyar Asri'],
            ['name' => 'Joko', 'username' => 'joko1', 'address' => 'Gunung Anyar Asri'],
            ['name' => 'Rosid', 'username' => 'rosid1', 'address' => 'Gunung Anyar Sawah'],
            ['name' => 'Uyun', 'username' => 'uyun1', 'address' => 'Gunung Anyar Tambak'],
            ['name' => 'Misnan', 'username' => 'misnan1', 'address' => 'Gunung Anyar Tambak'],
            ['name' => 'Lidia', 'username' => 'lidia1', 'address' => 'Gunung Anyar Tambak'],
            ['name' => 'Sakur', 'username' => 'sakur1', 'address' => 'Gunung Anyar Tambak 1'],
            ['name' => 'Umroh', 'username' => 'umroh1', 'address' => 'Gunung Anyar Tambak 1'],
            ['name' => 'Torika', 'username' => 'torika1', 'address' => 'Gunung Anyar Tambak 1'],
            ['name' => 'Nur Hayati', 'username' => 'nurhayati1', 'address' => 'Gunung Anyar Tambak 1'],
            ['name' => 'Kholik', 'username' => 'kholik1', 'address' => 'Gunung Anyar Tambak 1'],
            ['name' => 'Mar', 'username' => 'mar01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Sri Wahyuni', 'username' => 'sriwahyuni01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Khoiroh', 'username' => 'khoiroh01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Feri', 'username' => 'feri01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Faris', 'username' => 'faris01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Lailatur Umroh', 'username' => 'lailaturumroh01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Rehan', 'username' => 'rehan01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Mardiyah', 'username' => 'mardiyah01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Yatimah', 'username' => 'yatimah01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Tiara', 'username' => 'tiara01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Selam', 'username' => 'selam01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Suudah', 'username' => 'suudah01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Tamara', 'username' => 'tamara01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Desi', 'username' => 'desi01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Adam', 'username' => 'adam01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Fitriyah', 'username' => 'fitriyah01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Maschan', 'username' => 'maschan01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Khoiroh', 'username' => 'khoiroh02', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Bathin', 'username' => 'bathin01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Supardi', 'username' => 'supardi01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Wandi', 'username' => 'wandi01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Dewi Aisah', 'username' => 'dewaaisah01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Machulah', 'username' => 'machulah01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Uswati', 'username' => 'uswati01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Misnaldi', 'username' => 'misnaldi01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Nahrowi', 'username' => 'nahrowi01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Triyan', 'username' => 'triyan01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Siti Kalimah', 'username' => 'sitikalimah01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Raja', 'username' => 'raja01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Rama', 'username' => 'rama01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Arir', 'username' => 'arir01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Fauzi', 'username' => 'fauzi01', 'address' => 'GN. A TAMBAK 1'],
            ['name' => 'Hisyam', 'username' => 'hisyam01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Andika', 'username' => 'andika01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Nur Hasan', 'username' => 'nurhasan01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Chika', 'username' => 'chika01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Adib', 'username' => 'adib01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Putri', 'username' => 'putri01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Dina', 'username' => 'dina01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Alya', 'username' => 'alya01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Jabal', 'username' => 'jabal01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Alfat', 'username' => 'alfat01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Karis', 'username' => 'karis01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Zami', 'username' => 'zami01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Sali', 'username' => 'sali01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Saipul', 'username' => 'saipul01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Asrifah', 'username' => 'asrifah01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Khudin', 'username' => 'khudin01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Wahid', 'username' => 'wahid01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Rt 5 Wawad', 'username' => 'rt5wawad01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Kiran', 'username' => 'kiran01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Maimunah', 'username' => 'maimunah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Pasikah', 'username' => 'pasikah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Legina', 'username' => 'legina01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Agus', 'username' => 'agus01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Hariyono', 'username' => 'hariyono01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Wahidah', 'username' => 'wahidah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Sulaiman', 'username' => 'sulaiman01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Kiptiyah', 'username' => 'kiptiyah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Asari', 'username' => 'asari01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Asrofin', 'username' => 'asrofin01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Ulwiyah', 'username' => 'ulwiyah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Ifah', 'username' => 'ifah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Abib', 'username' => 'abib01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Sodik', 'username' => 'sodik01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Sulastri', 'username' => 'sulastri01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Kirom', 'username' => 'kirom01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Nimah', 'username' => 'nimah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Somo', 'username' => 'somo01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Anik Umroh', 'username' => 'anikumroh01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Roni', 'username' => 'roni01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Ambar', 'username' => 'ambar01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Cantik', 'username' => 'cantik01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Sihab', 'username' => 'sihab01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Atiq', 'username' => 'atiq01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Arfin', 'username' => 'arfin01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Dewi', 'username' => 'dewi01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Alfin', 'username' => 'alfin01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Putri K', 'username' => 'putrik01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Maulana', 'username' => 'maulana01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Afifah', 'username' => 'afifah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Akiyah', 'username' => 'akiyah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Syaroh', 'username' => 'syaroh01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Samiran', 'username' => 'samiran01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Abidah', 'username' => 'abidah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Jumadi', 'username' => 'jumadi01', 'address' => 'Gn. Anyar'],
            ['name' => 'Jakariyah', 'username' => 'jakariyah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Kasanah', 'username' => 'kasanah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Andri', 'username' => 'andri01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Zubaidah', 'username' => 'zubaidah01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Ach Sudiaryo', 'username' => 'achsudiaryo01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Alfiyah', 'username' => 'alfiyah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Lutfia', 'username' => 'lutfia01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Laili', 'username' => 'laili01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Wiwin', 'username' => 'wiwin01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Hamiyah', 'username' => 'hamiyah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Adidi', 'username' => 'adidi01', 'address' => 'Gn. A Tambak 3/88'],
            ['name' => 'Nur Chakimah', 'username' => 'nurchakimah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Chusniyati', 'username' => 'chusniyati01', 'address' => 'Gn. A Tambak 3/88'],
            ['name' => 'Rozi', 'username' => 'rozi01', 'address' => 'Gn. A Tambak'],
            ['name' => 'Totok S', 'username' => 'totoks01', 'address' => 'Gn. A Tambak'],
            ['name' => 'Ainur M', 'username' => 'ainurm01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Richana', 'username' => 'richana01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Solikah', 'username' => 'solikah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'H Cafid', 'username' => 'hcafid01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'H Zahroh', 'username' => 'hzahroh01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Sarse', 'username' => 'sarse01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Masruroh', 'username' => 'masruroh01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'H Salbiyah', 'username' => 'hsalbiyah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'H Giono', 'username' => 'hgiono01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Nur Hudin', 'username' => 'nurhudin01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Joko Sugiarto', 'username' => 'jokosugiarto01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Hj Liana', 'username' => 'hjliana01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Mariyam', 'username' => 'mariyam01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Dartok', 'username' => 'dartok01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Rofah', 'username' => 'rofah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Arip', 'username' => 'arip01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Nasipah', 'username' => 'nasipah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Lilik Zainab', 'username' => 'lilikzainab01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Al Fatimah', 'username' => 'alfatimah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'H Munawaroh', 'username' => 'hmunawaroh01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Mafruchah', 'username' => 'mafruchah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'H Saropaj', 'username' => 'hsaropaj01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'M Chusnul L', 'username' => 'mchusnull01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Hj Hasibah', 'username' => 'hjhasibah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Khoiriyah', 'username' => 'khoiriyah01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Masjid Qowiyul Islam', 'username' => 'masjidqowiyulislam01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Saifaul', 'username' => 'saifaul01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Sulis', 'username' => 'sulis01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Khoirohman', 'username' => 'khoirohman01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Alan', 'username' => 'alan01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Kholili', 'username' => 'kholili01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'M Amirul M', 'username' => 'mamirulm01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Sukron', 'username' => 'sukron01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Muniro', 'username' => 'muniro01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Nadida', 'username' => 'nadida01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Anis Saati', 'username' => 'anissaati01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Pii', 'username' => 'pii01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Miryani', 'username' => 'miryani01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Abd Pake', 'username' => 'abdpake01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Adid Insan', 'username' => 'adidinsan01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'HJ Farida', 'username' => 'hjfarida01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Maisaroh', 'username' => 'maisaroh01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'SD Dahlanuddin', 'username' => 'sddahlanuddin01', 'address' => 'Gn. A Tambak 1'],
            ['name' => 'Rifaah', 'username' => 'rifaah01', 'address' => 'Gn. A Tambak 1/54'],
            ['name' => 'Suyekno', 'username' => 'suyekno01', 'address' => 'Gn. A Tambak 11'],
            ['name' => 'Nurul', 'username' => 'nurul01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Kamim', 'username' => 'kamim01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Anggi', 'username' => 'anggi01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Nakson', 'username' => 'nakson01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Mudakuroh', 'username' => 'mudakuroh01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Aini', 'username' => 'aini01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Suhud', 'username' => 'suhud01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Jono', 'username' => 'jono01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'TR Dahlaludin', 'username' => 'trdahlaludin01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Hj Farochah', 'username' => 'hjfarochah01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Mauduah', 'username' => 'mauduah01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Hj Farichah', 'username' => 'hjfarichah01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Wahab', 'username' => 'wahab01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Moch Habari', 'username' => 'mochhabari01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Pakde Sakur', 'username' => 'pakdesakur01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Endang', 'username' => 'endang01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Kurnia', 'username' => 'kurnia01', 'address' => 'Gn. A Tambak 2'],
            ['name' => 'Patimah', 'username' => 'patimah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Khoiron', 'username' => 'khoiron01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Paiman', 'username' => 'paiman01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'H Zumaroh', 'username' => 'hzumaroh01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Nurus', 'username' => 'nurus01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Jahudin', 'username' => 'jahudin01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'P Mul', 'username' => 'pmul01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Artimuna', 'username' => 'artimuna01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Windi', 'username' => 'windi01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Rian', 'username' => 'rian01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Samid', 'username' => 'samid01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Jai', 'username' => 'jai01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Lulik Zulfa', 'username' => 'lulikzulfa01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Maisaroh', 'username' => 'maisaroh02', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Arofi', 'username' => 'arofi01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Wati', 'username' => 'wati01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Ulul', 'username' => 'ulul01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Miskan', 'username' => 'miskan01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Sudarse', 'username' => 'sudarse01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'M Ajis', 'username' => 'majis01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Misnah', 'username' => 'misnah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'H Munir', 'username' => 'hmunir01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Rochimah', 'username' => 'rochimah01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Bayu', 'username' => 'bayu01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Hasan', 'username' => 'hasan01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Sutrisno', 'username' => 'sutrisno01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Sadam', 'username' => 'sadam01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Mahfiroh', 'username' => 'mahfiroh01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Pirnanda', 'username' => 'pirnanda01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Supina', 'username' => 'supina01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Saimad', 'username' => 'saimad01', 'address' => 'Gn. A Tambak 3'],
            ['name' => 'Thohiron', 'username' => 'thohiron01', 'address' => 'Gn. A Tambak 4'],
            ['name' => 'Jadid', 'username' => 'jadid01', 'address' => 'Gn. A Tambak 4'],
            ['name' => 'Akhmad', 'username' => 'akhmad01', 'address' => 'Gununganyar'],
            ['name' => 'Arip', 'username' => 'arip02', 'address' => 'Jagir Wonokromo'],
            ['name' => 'Intan', 'username' => 'intan01', 'address' => 'Jl Rambutan Candra Sidoarjo'],
            ['name' => 'Samsul', 'username' => 'samsul01', 'address' => 'Perum Alam'],
            ['name' => 'Samsul Huda', 'username' => 'samsulhuda01', 'address' => 'Perum Alam Gn. A'],
            ['name' => 'Indah', 'username' => 'indah01', 'address' => 'Pesona Alam Gn. A'],
            ['name' => 'Tri', 'username' => 'tri01', 'address' => 'Rungkut Asri'],
            ['name' => 'Bu Hari', 'username' => 'buhari01', 'address' => 'Rungkut Mananggal'],
            ['name' => 'Aris', 'username' => 'aris01', 'address' => 'SBY'],
            ['name' => 'Abd Muin', 'username' => 'abdmuin01', 'address' => 'Segoro Tambak'],
            ['name' => 'Rudi', 'username' => 'rudi01', 'address' => 'Sentral Park'],
            ['name' => 'Budi Sentral', 'username' => 'budisentral01', 'address' => 'Sentral Park'],
            ['name' => 'Kristina', 'username' => 'kristina01', 'address' => 'Taman Wiguna Sel'],
            ['name' => 'Satar', 'username' => 'satar01', 'address' => 'Tambak Oso'],
            ['name' => 'Mulyati', 'username' => 'mulyati01', 'address' => 'Tambak Oso'],
            ['name' => 'Muayadah', 'username' => 'muayadah01', 'address' => 'Tambak Oso'],
            ['name' => 'Edi', 'username' => 'edi01', 'address' => 'Tambak Oso'],
            ['name' => 'Rohillah', 'username' => 'rohillah01', 'address' => 'Tambak Oso'],
            ['name' => 'Naryo', 'username' => 'naryo01', 'address' => 'Tambak Oso'],
            ['name' => 'Amirul', 'username' => 'amirul02', 'address' => 'Tambak Oso Sidoarjo'],
            ['name' => 'Kelurahan Gat', 'username' => 'kelurahangat01', 'address' => 'Wiguna'],
            ['name' => 'B Sugeng', 'username' => 'bsugeng01', 'address' => 'Wiguna Sel'],
            ['name' => 'Bu Rudi', 'username' => 'burudi01', 'address' => 'Wiguna Sel'],
            ['name' => 'Bu Budi P', 'username' => 'bubudip01', 'address' => 'Wiguna Sel'],
            ['name' => 'Dian', 'username' => 'dian01', 'address' => 'Wiguna Sel RW 3'],
            ['name' => 'Dedy', 'username' => 'dedy01', 'address' => 'Wiguna Sel RW 3'],
            ['name' => 'Bu Gun', 'username' => 'bugun01', 'address' => 'Wiguna Sel RW 3'],
            ['name' => 'Parno', 'username' => 'parno01', 'address' => 'Wiguna Sel RW 3'],
            ['name' => 'Bu Ibrahim', 'username' => 'buibrahim01', 'address' => 'Wiguna Sel RW 3'],
            ['name' => 'Bu Markus', 'username' => 'bumarkus01', 'address' => 'Wiguna Tengah'],
            ['name' => 'Bu Sukirman', 'username' => 'busukirman01', 'address' => 'Wiguna Tengah'],
            ['name' => 'Bu Wahyu', 'username' => 'buwahyu01', 'address' => 'Wiguna Tengah RW 2'],
            ['name' => 'Bu Budi', 'username' => 'bubudi02', 'address' => 'Witeng']
        ];
        foreach ($users as $user) {
            User::factory()->create([
                'name' => $user['name'],
                'address' => $user['address'],
                'email' => null,
                'username' => $user['username'],
                'password' => bcrypt('password'), // Default password untuk semua user
                'role_id' => 1, // Set default role_id
                'branch_id' => 1, // Set default branch_id
                'saldo' => 0,
            ]);
        }
    }
}
